version: "3"

services:
  next:
    container_name: next
    expose:
      - 3000
    build:
      context: ./barristar
      dockerfile: Dockerfile
    image: with-docker-multi-env-production

  nginx:
    build: ./nginx
    expose:
      - 80
    depends_on: ["next"]
    links:
      - next
      - nginx-proxy
      - letsencrypt
    environment:
      - VIRTUAL_HOST=integralpro.com.bo,www.integralpro.com.bo
      - LETSENCRYPT_HOST=integralpro.com.bo,www.integralpro.com.bo
    restart: always

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
volumes:
  certs:
  html:
  vhostd: